# Generated by Nodus from nodus.toml. Do not edit.
include_guard(GLOBAL)

CPMAddPackage(
  NAME cli11
  GITHUB_REPOSITORY "CLIUtils/CLI11"
  GIT_TAG "v2.4.2"
)

CPMAddPackage(
  NAME cpr
  GITHUB_REPOSITORY "libcpr/cpr"
  GIT_TAG "1.10.x"
  OPTIONS
    "CPR_CURL_USE_LIBPSL OFF"
)

CPMAddPackage(
  NAME indicators
  GITHUB_REPOSITORY "p-ranav/indicators"
  GIT_TAG "v2.3"
)

